### ISSUE TITLE
product quantity

### ISSUE THREAD

**Issue by Duyen9904** [trunghung03/SWP_Project#17]
reduce quantity for shell, diamond, product when have a "Paid" order

**Comment by hoangminhle1108** [comment]
cái DB chưa rõ (Diamond tbl hong có quantity , Shell tbl kiểu chưa có phân loại rõ lắm - shellID thôi nhma không biết shell đó loại gì GOld, Silver ,, ....)
![Screenshot 2024-07-01 112811](https://github.com/trunghung03/SWP_Project/assets/147319801/372dc292-199a-4de5-9de5-91e554a036b5)
![Screenshot 2024-07-01 112845](https://github.com/trunghung03/SWP_Project/assets/147319801/db009901-ddf9-4d99-a940-e55aac9a84f4)

**Comment by trunghung03** [comment]
Vì trong diamond table có cái CertificateScan nên mỗi kim cương sẽ được quản lý trong 1 table riêng.

Shell là để quản lý số lượng, còn shellmaterial thì khách hàng sẽ tự chọn trong orderdetail

**Comment by hoangminhle1108** [comment]
kiểu muốn trừ số lượng thì mình làm thế nào với diamond anh ... 

với còn shell thì làm sao để biết số lượng của Gold, Silver, ... còn bao nhiêu để làm được anh ...
