### ISSUE TITLE
add employee validation

### ISSUE THREAD

**Issue by Duyen9904** [trunghung03/SWP_Project#20]
![image](https://github.com/trunghung03/SWP_Project/assets/123815528/20881e3c-b420-4859-8dc0-ea4bff920484)
remove option admin
![image](https://github.com/trunghung03/SWP_Project/assets/123815528/ccece0bc-60b1-4950-802a-bf2374bec5f5)
validation for all fields
LastName, FirstName: just alphabet (no number)
Phonenumber cannot contain alphabet
Email format: just accept @gmail.com
Address required more than 20 chracters

**Comment by trunghung03** [comment]
Already fixed
