### ISSUE TITLE
Change to "Continue with Google"

### ISSUE THREAD

**Issue by trunghung03** [trunghung03/SWP_Project#39]
"Sign in with Google" will instead sign up and create a new User account if it doesn't exist. 

![ảnh](https://github.com/user-attachments/assets/d339ed5a-f4cf-4a20-a530-bccf58348250)

Because the Google button does both Sign up and Sign in, I propose changing "Sign in with Google" to be "Continue with Google" (As shown in example by Reddit).
![ảnh](https://github.com/user-attachments/assets/c1dab5af-492e-451f-be23-9ccb88657d6c)

**Comment by Trannhbse182378** [comment]
"Sign in with Google" is default of Google's library can not change
