### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by Duyen9904** [trunghung03/SWP_Project#41]
![image](https://github.com/user-attachments/assets/b91d0dd2-e9ee-4824-acf9-b8857a21e5a3)
![image](https://github.com/user-attachments/assets/ae0e7491-d37e-4299-9bce-5ea82d8403a2)
pdf should take data of diamond/subdiamond list instead of attribute list

**Comment by MichaelDang110104** [comment]
Done diamond pdf
