### ISSUE TITLE
nothing in order history

### ISSUE THREAD

**Issue by Duyen9904** [trunghung03/SWP_Project#47]
![image](https://github.com/user-attachments/assets/7c67926b-d28d-4093-80d0-0cd0e0ee8765)
no noti when add diamond product to cart

![image](https://github.com/user-attachments/assets/41bff348-1232-465f-bdff-147a2615dd51)
Minh viet api get order cho customer r Tran chinh lai thanh api do
Do vua moi pagination cai purchase order do nen gio error

**Comment by hoangminhle1108** [comment]
done API
