### ISSUE TITLE
sort order list manager

### ISSUE THREAD

**Issue by Duyen9904** [trunghung03/SWP_Project#54]
![image](https://github.com/user-attachments/assets/a58493c8-62c7-4a64-95b9-58e01d27cedd)

**Comment by Duyen9904** [comment]
![image](https://github.com/user-attachments/assets/20442657-9383-433e-96dd-d0e811c8253e)
manager ccannot search

**Comment by Duyen9904** [comment]
k search dc khi o page 1

**Comment by Duyen9904** [comment]
![image](https://github.com/user-attachments/assets/4f59eefc-4dd1-4104-8dfe-9dd6ab752381)
also sales staff

**Comment by hoangminhle1108** [comment]
done add new api for Search

**Comment by Duyen9904** [comment]
done thi close di fennn
