### ISSUE TITLE
Fix api to get product that is not out of stock

### ISSUE THREAD

**Issue by Trannhbse182378** [trunghung03/SWP_Project#55]
![image](https://github.com/user-attachments/assets/8f633b80-ff82-475f-8002-1c300e5e7c58)

![image](https://github.com/user-attachments/assets/056c59ec-fc2d-4a35-9d23-ee59272bca27)

Fix 2 api above to get only product is not out of stock

**Comment by Duyen9904** [comment]
tinh nang soldout nha
