### ISSUE TITLE
collection list dislplay

### ISSUE THREAD

**Issue by Duyen9904** [trunghung03/SWP_Project#60]
manage collection thêm cột image vô
minh tra them img link vo dto neu chua tra cho Duy lam

**Comment by hoangminhle1108** [comment]
là sao bạn có imgLink rồi mè
![image](https://github.com/user-attachments/assets/bfd412bf-99e5-4baf-982b-49c2b55ac6b6)

**Comment by Duyen9904** [comment]
thi` t ghi neu' chua co ma

**Comment by hoangminhle1108** [comment]
giờ tới bạn căng hở .... ý là bị lỗi gì á để fix FE lun
Update kh đc hở

**Comment by Duyen9904** [comment]
thêm cột đó vô collection thoi à, quá ez...

**Comment by MichaelDang110104** [comment]
Done display link
