### ISSUE TITLE
search order

### ISSUE THREAD

**Issue by Duyen9904** [trunghung03/SWP_Project#61]
thanh search trang order list lỗi, nó search orderid trong cái pagination hiện tại chứ ko search trong all order

**Comment by Duyen9904** [comment]
manager + sales staff

**Comment by hoangminhle1108** [comment]
làm api rồi mà

**Comment by Duyen9904** [comment]
coi lafm r thi done issue i, chac tai Tran test tren deploy co may cai chua deploy be len lai, sao cang
https://ih1.redbubble.net/image.1311748206.2721/bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8.jpg

**Comment by hoangminhle1108** [comment]
ý là chưa làm FE mới làm BE à
