### ISSUE TITLE
manager diamond

### ISSUE THREAD

**Issue by Duyen9904** [trunghung03/SWP_Project#63]
+ main diamond mua xong là mất ko hiện trong table, làm cho hiện full diamond xong thêm cột true false để biết cục nào sold rồi
+ download pdf down được mà file ko có data j hết
+ thanh search ko search đc
Minh chỉnh search nha, 2 kia t coi. tại t quậy :))

**Comment by hoangminhle1108** [comment]
là sao bạn, cụ thể hơn đc hong =)))))

**Comment by Duyen9904** [comment]
commit be cua diamond len di
